services:
  - type: web
    name: visionboard-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: TMDB_API_TOKEN
        sync: false
      - key: CORS_ORIGIN
        sync: false
